import { inject, Injectable } from '@angular/core';
import { GeneralStore } from '@app/core/services/general-store.service';
import { Option } from '@app/shared/commonTypes';
import { CASE_STATES } from '@app/shared/constants/case-states';
import { TableColumn } from '@app/shared/components/case-list-table/case-list-table.component';
import { NUXEO_SCHEMA_FIELDS } from '@app/shared/constants/nuxeo-schema-fields';

export const states: Option[] = CASE_STATES;

const REFERENCES_TABLE_NAME = 'REFERENCES';
const HANDLINGS_TABLE_NAME = 'HANDLINGS';
const ARBETSMATERIAL_TABLE_NAME = 'ARBETSMATERIAL';
const HANDLINGAR_TABLE_NAME_GRID = 'HANDLINGAR_GRID';

@Injectable({ providedIn: 'root' })
export class ConstantProvider {
  private readonly generalStore = inject(GeneralStore);

  private label(key: string): string {
    return this.generalStore.getValue(key) ?? '';
  }

  readonly referencesColumnsConfig: TableColumn[] = [
    {
      label: this.label('label.ui.schema.arende.arendenummer'),
      key: 'caseNumber',
      searchField: 'arende_arendenummer',
      asLink: true,
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.arendemening'),
      key: 'caseTitle',
      searchField: 'arende_arendemening',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.internArendereferens.referenstyp'),
      key: 'displayType',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.internArendereferens.referenskommentar'),
      key: 'comment',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.motpart'),
      key: 'counterparty',
      searchField: 'arende_arendepart',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.arendetyp'),
      key: 'arendetyp',
      searchField: 'arende_arendetyp',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.arendestatus'),
      key: 'arendestatus',
      searchField: 'arende_arendestatus',
      visible: false,
    },
    {
      label: this.label('label.document.type.handlaggningsstatus'),
      key: 'handlaggningsstatus',
      searchField: 'arende_handlaggningsstatus',
      visible: false,
    },
    {
      label: 'Ärendeprocess',
      key: 'behorighetsstatus',
      searchField: 'arende_behorighetsstatus',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.riktning'),
      key: 'riktning',
      searchField: 'arende_riktning',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.sekretess'),
      key: 'sekretess',
      searchField: 'arende_sekretess',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.sakerhetsskyddsklassificering'),
      key: 'sakerhetsskyddsklassificering',
      searchField: 'arende_sakerhetsskyddsklassificering',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.motpart'),
      key: 'arendepart',
      sortField: NUXEO_SCHEMA_FIELDS.arende.arendepart,
      searchField: 'arende_arendepart',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.ansvarigOrganisatoriskEnhet'),
      key: 'ansvarigEnhet',
      searchField: 'arende_ansvarig_organisatorisk_enhet',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.ansvarigOrganisationsenhetschef'),
      key: 'ansvarigChef',
      searchField: 'arende_ansvarig_organisationsenhetschef',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.ansvarigHandlaggare'),
      key: 'handlaggare',
      searchField: 'arende_ansvarig_handlaggare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.medhandlaggare'),
      key: 'medhandlaggare',
      searchField: 'arende_medhandlaggare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.granskare'),
      key: 'granskare',
      searchField: 'arende_granskare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.internArendemening'),
      key: 'internArendemening',
      searchField: 'arende_intern_arendemening',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.jkKommentar'),
      key: 'jkKommentar',
      searchField: 'arende_jk_kommentar',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.allmanKommentar'),
      key: 'allmanKommentar',
      searchField: 'arende_allman_kommentar',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.bevarasGallras'),
      key: 'bevarasGallras',
      searchField: 'arende_bevaras_gallras',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.innehallerPersonuppgifterGdpr'),
      key: 'innehallerPersonuppgifter',
      searchField: 'arende_innehaller_personuppgifter_gdpr',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.arendetArkiveratDatum'),
      key: 'arkiveratDatum',
      searchField: 'arende_arendet_arkiverat_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.arendetGallratDatum'),
      key: 'gallratDatum',
      searchField: 'arende_arendet_gallrat_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.arendetMakuleratDatum'),
      key: 'makuleratDatum',
      searchField: 'arende_arendet_makulerat_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.handlaggningPaborjadDatum'),
      key: 'handlaggningPaborjad',
      searchField: 'arende_handlaggning_paborjad',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.handlaggningAvslutadDatum'),
      key: 'handlaggningAvslutad',
      searchField: 'arende_handlaggning_avslutad',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.beslutatDatum'),
      key: 'beslutatDatum',
      searchField: 'arende_beslutat_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.beslutExpedieratDatum'),
      key: 'beslutExpedieratDatum',
      searchField: 'arende_beslut_expedierat_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.arendestatus'),
      key: 'status',
      searchField: 'arende_arendestatus',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.arendetRegistreratDatum'),
      key: 'date',
      searchField: 'arende_arendet_registrerat_datum',
      visible: true,
    },
    {
      label: this.label('label.dublincore.created'),
      key: 'created',
      searchField: 'dc_created',
      visible: false,
    },
    {
      label: this.label('label.dublincore.modified'),
      key: 'modified',
      searchField: 'dc_modified',
      visible: false,
    },
    {
      label: this.label('label.dublincore.lastContributor'),
      key: 'lastContributor',
      searchField: 'dc_lastContributor',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.arende.ansvarigHandlaggare'),
      key: 'responsibleOfficer',
      searchField: 'arende_ansvarig_handlaggare',
      visible: true,
    },
  ].map(col => ({ ...col, tableName: REFERENCES_TABLE_NAME }));

  readonly handlingsColumnsConfig: TableColumn[] = [
    {
      label: this.label('label.ui.schema.handling.handlingsnummer'),
      key: 'handlingNumber',
      searchField: 'handling_handlingsnummer',
      asLink: true,
      visible: true,
    },
    {
      label: this.label('label.ui.schema.handling.handlingsnamn'),
      key: 'handlingTitle',
      searchField: 'handling_handlingsnamn',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.internHandlingsreferens.referenstyp'),
      key: 'displayType',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.arende.internHandlingsreferens.referenskommentar'),
      key: 'comment',
      visible: true,
    },
    { label: 'Avsandare/Mottagare', key: 'counterparty', visible: true },
    {
      label: this.label('label.ui.schema.handling.handlingsriktning'),
      key: 'riktning',
      searchField: 'handling_handlingsriktning',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.handling.inkommenDatum'),
      key: 'date',
      searchField: 'handling_inkommen_datum',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.handling.ansvarigHandlaggare'),
      key: 'responsibleOfficer',
      searchField: 'handling_ansvarig_handlaggare',
      visible: true,
    },
    {
      label: this.label('label.ui.schema.handling.handlingsstatus'),
      key: 'handlingStatus',
      searchField: 'handling_handlingsstatus',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.sekretess'),
      key: 'handlingSekretess',
      searchField: 'handling_sekretess',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.sakerhetsskyddsklassificering'),
      key: 'handlingSakerhetsskyddsklassificering',
      searchField: 'handling_sakerhetsskyddsklassificering',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.bevarasGallras'),
      key: 'handlingBevarasGallras',
      searchField: 'handling_bevaras_gallras',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.innehallerPersonuppgifterGdpr'),
      key: 'handlingInnehallerPersonuppgifter',
      searchField: 'handling_innehaller_personuppgifter_gdpr',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.beslutsfattare'),
      key: 'handlingBeslutsfattare',
      searchField: 'handling_beslutsfattare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.ansvarigOrganisatoriskEnhet'),
      key: 'handlingAnsvarigEnhet',
      searchField: 'handling_ansvarig_organisatorisk_enhet',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.medhandlaggare'),
      key: 'handlingMedhandlaggare',
      searchField: 'handling_medhandlaggare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.granskare'),
      key: 'handlingGranskare',
      searchField: 'handling_granskare',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.granskningsdatum'),
      key: 'handlingGranskningsdatum',
      searchField: 'handling_granskningsdatum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.granskningskommentar'),
      key: 'handlingGranskningskommentar',
      searchField: 'handling_granskningskommentar',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.upprattadDatum'),
      key: 'handlingUpprattadDatum',
      searchField: 'handling_upprattad_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.arkiveradDatum'),
      key: 'handlingArkiveradDatum',
      searchField: 'handling_arkiverad_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.gallradDatum'),
      key: 'handlingGallradDatum',
      searchField: 'handling_gallrad_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.makuleradDatum'),
      key: 'handlingMakuleradDatum',
      searchField: 'handling_makulerad_datum',
      visible: false,
    },
    {
      label: this.label('label.ui.schema.handling.signerad'),
      key: 'handlingSignerad',
      searchField: 'handling_signerad',
      visible: false,
    },
    {
      label: 'Skapad av',
      key: 'handlingCreatedBy',
      searchField: 'dc_creator',
      visible: false,
    },
    {
      label: this.label('label.dublincore.modified'),
      key: 'handlingModified',
      searchField: 'dc_modified',
      visible: false,
    },
  ].map(col => ({ ...col, tableName: HANDLINGS_TABLE_NAME }));

  readonly arbetsmaterialTableConfig: TableColumn[] = [
    {
      id: 'title',
      label: this.label('label.dublincore.title'),
      key: 'title',
      sortField: NUXEO_SCHEMA_FIELDS.dc.title,
      visible: true,
      asLink: true,
    },
    { id: 'type', label: this.label('label.type'), key: 'type', sortField: 'type', visible: true },
    {
      id: 'lastModified',
      label: this.label('label.dublincore.modified'),
      key: 'lastModified',
      sortField: NUXEO_SCHEMA_FIELDS.dc.modified,
      visible: true,
    },
    {
      id: 'created',
      label: this.label('label.dublincore.created'),
      key: 'created',
      sortField: NUXEO_SCHEMA_FIELDS.dc.created,
      visible: false,
    },
    {
      id: 'avsandare',
      label: this.label('label.ui.schema.handling.avsandare'),
      key: 'avsandare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.avsandare,
      class: 'w-[20%]',
      visible: true,
    },
    {
      id: 'inkommet',
      label: this.label('label.ui.schema.handling.inkommenDatum'),
      key: 'inkommet',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
      class: 'w-[20%]',
      visible: true,
    },
    {
      id: 'inkanalVia',
      label: this.label('label.ui.schema.handling.inkanalVia'),
      key: 'inkanalVia',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkanalVia,
      visible: false,
    },
    {
      id: 'utkanalVia',
      label: this.label('label.ui.schema.handling.utkanalVia'),
      key: 'utkanalVia',
      sortField: NUXEO_SCHEMA_FIELDS.handling.utkanalVia,
      visible: false,
    },
    { id: 'status', label: this.label('label.state'), key: 'status', sortField: 'status', visible: false },
    {
      id: 'riktning',
      label: this.label('label.ui.schema.handling.handlingsriktning'),
      key: 'riktning',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingsriktning,
      visible: false,
    },
  ].map(column => ({ ...column, tableName: ARBETSMATERIAL_TABLE_NAME }));

  readonly handlingarTableConfig: TableColumn[] = [
    {
      id: 'title',
      label: this.label('label.dublincore.title'),
      key: 'title',
      sortField: NUXEO_SCHEMA_FIELDS.dc.title,
      visible: true,
      asLink: true,
    },
    { id: 'type', label: this.label('label.type'), key: 'type', sortField: 'type', visible: true },
    {
      id: 'lastModified',
      label: this.label('label.dublincore.modified'),
      key: 'lastModified',
      sortField: NUXEO_SCHEMA_FIELDS.dc.modified,
      visible: true,
    },
    {
      id: 'handlingsnamn',
      label: this.label('label.ui.schema.handling.handlingsnamn'),
      key: 'handlingsnamn',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingsnamn,
      visible: false,
    },
    {
      id: 'handlingsnummer',
      label: this.label('label.ui.schema.handling.handlingsnummer'),
      key: 'handlingsnummer',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingsnummer,
      visible: false,
    },
    {
      id: 'arendenummer',
      label: this.label('label.ui.schema.handling.arendenummer'),
      key: 'arendenummer',
      sortField: NUXEO_SCHEMA_FIELDS.handling.arendenummer,
      visible: false,
    },
    {
      id: 'inkommen',
      label: this.label('label.ui.schema.handling.inkommenDatum'),
      key: 'inkommen',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
      visible: false,
    },
    {
      id: 'utgaende',
      label: this.label('label.ui.schema.handling.utgaendeDatum'),
      key: 'utgaende',
      sortField: NUXEO_SCHEMA_FIELDS.handling.utgaendeDatum,
      visible: false,
    },
    {
      id: 'handlingType',
      label: this.label('label.ui.schema.handling.handlingstyp'),
      key: 'handlingType',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingstyp,
      visible: false,
    },
    {
      id: 'handlingStatus',
      label: this.label('label.ui.schema.handling.handlingsstatus'),
      key: 'handlingStatus',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingsstatus,
      visible: false,
    },
    {
      id: 'beslutsfattare',
      label: this.label('label.ui.schema.handling.beslutsfattare'),
      key: 'beslutsfattare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.beslutsfattare,
      visible: false,
    },
    {
      id: 'avsandare',
      label: this.label('label.ui.schema.handling.avsandare'),
      key: 'avsandare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.avsandare,
      class: 'w-[20%]',
      visible: true,
    },
    {
      id: 'inkommetDisplay',
      label: this.label('label.ui.schema.handling.inkommenDatum'),
      key: 'inkommet',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
      class: 'w-[20%]',
      visible: true,
    },
    {
      id: 'inkanalVia',
      label: this.label('label.ui.schema.handling.inkanalVia'),
      key: 'inkanalVia',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkanalVia,
      visible: false,
    },
    {
      id: 'utkanalVia',
      label: this.label('label.ui.schema.handling.utkanalVia'),
      key: 'utkanalVia',
      sortField: NUXEO_SCHEMA_FIELDS.handling.utkanalVia,
      visible: false,
    },
    {
      id: 'riktning',
      label: this.label('label.ui.schema.handling.handlingsriktning'),
      key: 'riktning',
      sortField: NUXEO_SCHEMA_FIELDS.handling.handlingsriktning,
      visible: false,
    },
    {
      id: 'sekretess',
      label: this.label('label.ui.schema.handling.sekretess'),
      key: 'sekretess',
      sortField: NUXEO_SCHEMA_FIELDS.handling.sekretess,
      visible: false,
    },
    {
      id: 'sakerhetsskyddsklassificering',
      label: this.label('label.ui.schema.handling.sakerhetsskyddsklassificering'),
      key: 'sakerhetsskyddsklassificering',
      sortField: NUXEO_SCHEMA_FIELDS.handling.sakerhetsskyddsklassificering,
      visible: false,
    },
    {
      id: 'ansvarigHandlaggare',
      label: this.label('label.ui.schema.handling.ansvarigHandlaggare'),
      key: 'ansvarigHandlaggare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.ansvarigHandlaggare,
      visible: false,
    },
    {
      id: 'ansvarigEnhet',
      label: this.label('label.ui.schema.handling.ansvarigOrganisatoriskEnhet'),
      key: 'ansvarigEnhet',
      sortField: NUXEO_SCHEMA_FIELDS.handling.ansvarigOrganisatoriskEnhet,
      visible: false,
    },
    {
      id: 'medhandlaggare',
      label: this.label('label.ui.schema.handling.medhandlaggare'),
      key: 'medhandlaggare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.medhandlaggare,
      visible: false,
    },
    {
      id: 'granskare',
      label: this.label('label.ui.schema.handling.granskare'),
      key: 'granskare',
      sortField: NUXEO_SCHEMA_FIELDS.handling.granskare,
      visible: false,
    },
    {
      id: 'granskningsdatum',
      label: this.label('label.ui.schema.handling.granskningsdatum'),
      key: 'granskningsdatum',
      sortField: NUXEO_SCHEMA_FIELDS.handling.granskningsdatum,
      visible: false,
    },
    {
      id: 'granskningskommentar',
      label: this.label('label.ui.schema.handling.granskningskommentar'),
      key: 'granskningskommentar',
      sortField: NUXEO_SCHEMA_FIELDS.handling.granskningskommentar,
      visible: false,
    },
    {
      id: 'receivedDate',
      label: this.label('label.ui.schema.handling.inkommenDatum'),
      key: 'receivedDate',
      sortField: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
      visible: false,
    },
    {
      id: 'upprattadDatum',
      label: this.label('label.ui.schema.handling.upprattadDatum'),
      key: 'upprattadDatum',
      sortField: NUXEO_SCHEMA_FIELDS.handling.upprattadDatum,
      visible: false,
    },
    {
      id: 'deadline',
      label: this.label('label.ui.schema.handling.utgaendeDatum'),
      key: 'deadline',
      sortField: NUXEO_SCHEMA_FIELDS.handling.utgaendeDatum,
      visible: false,
    },
    {
      id: 'motpart',
      label: this.label('label.ui.schema.handling.mottagare'),
      key: 'motpart',
      sortField: NUXEO_SCHEMA_FIELDS.handling.mottagare,
      visible: false,
    },
    {
      id: 'kommentarer',
      label: this.label('label.ui.schema.handling.kommentarer'),
      key: 'kommentarer',
      sortField: NUXEO_SCHEMA_FIELDS.handling.kommentarer,
      visible: false,
    },
    {
      id: 'bevarasGallras',
      label: this.label('label.ui.schema.handling.bevarasGallras'),
      key: 'bevarasGallras',
      sortField: NUXEO_SCHEMA_FIELDS.handling.bevarasGallras,
      visible: false,
    },
    {
      id: 'innehallerPersonuppgifter',
      label: this.label('label.ui.schema.handling.innehallerPersonuppgifterGdpr'),
      key: 'innehallerPersonuppgifter',
      sortField: NUXEO_SCHEMA_FIELDS.handling.innehallerPersonuppgifterGdpr,
      visible: false,
    },
    {
      id: 'arkiveradDatum',
      label: this.label('label.ui.schema.handling.arkiveradDatum'),
      key: 'arkiveradDatum',
      sortField: NUXEO_SCHEMA_FIELDS.handling.arkiveradDatum,
      visible: false,
    },
    {
      id: 'gallradDatum',
      label: this.label('label.ui.schema.handling.gallradDatum'),
      key: 'gallradDatum',
      sortField: NUXEO_SCHEMA_FIELDS.handling.gallradDatum,
      visible: false,
    },
    {
      id: 'makuleradDatum',
      label: this.label('label.ui.schema.handling.makuleradDatum'),
      key: 'makuleradDatum',
      sortField: NUXEO_SCHEMA_FIELDS.handling.makuleradDatum,
      visible: false,
    },
    {
      id: 'signerad',
      label: this.label('label.ui.schema.handling.signerad'),
      key: 'signerad',
      sortField: NUXEO_SCHEMA_FIELDS.handling.signerad,
      visible: false,
    },
    {
      id: 'createdBy',
      label: 'Skapad av',
      key: 'createdBy',
      sortField: NUXEO_SCHEMA_FIELDS.dc.creator,
      visible: false,
    }, //doesn't have label on BE
    {
      id: 'counterparty',
      label: this.label('label.ui.schema.arende.motpart'),
      key: 'counterparty',
      sortField: NUXEO_SCHEMA_FIELDS.handling.mottagare,
      visible: false,
    },
  ].map(column => ({ ...column, tableName: HANDLINGAR_TABLE_NAME_GRID }));
}

export const CASE_PAGE_ACCORDION_STATE_KEY = 'casePageAccordionState';
export const CASE_PAGE_ACCORDION_DEFAULTS: Record<string, boolean> = {
  oversikt: true,
  process: true,
  details: false,
  email: false,
  customMetadata: false,
  actors: false,
  references: false,
  arbetsmaterial: false,
  handlingar: false,
};
