import { NUXEO_SCHEMA_FIELDS } from '@app/shared/constants/nuxeo-schema-fields';
export const arbetsmaterialSortFieldMap: Record<string, string> = {
  title: NUXEO_SCHEMA_FIELDS.dc.title,
  type: 'ecm:primaryType',
  lastModified: NUXEO_SCHEMA_FIELDS.dc.modified,
  created: NUXEO_SCHEMA_FIELDS.dc.created,
  avsandare: NUXEO_SCHEMA_FIELDS.handling.avsandare,
  inkommet: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
  status: 'ecm:currentLifeCycleState',
  riktning: NUXEO_SCHEMA_FIELDS.handling.handlingsriktning,
};

export const handlingarSortFieldMap: Record<string, string> = {
  title: NUXEO_SCHEMA_FIELDS.dc.title,
  type: 'ecm:primaryType',
  lastModified: NUXEO_SCHEMA_FIELDS.dc.modified,
  handlingsnamn: NUXEO_SCHEMA_FIELDS.handling.handlingsnamn,
  handlingsnummer: NUXEO_SCHEMA_FIELDS.handling.handlingsnummer,
  arendenummer: NUXEO_SCHEMA_FIELDS.handling.arendenummer,
  inkommen: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
  utgaende: NUXEO_SCHEMA_FIELDS.handling.utgaendeDatum,
  handlingType: NUXEO_SCHEMA_FIELDS.handling.handlingstyp,
  handlingStatus: NUXEO_SCHEMA_FIELDS.handling.handlingsstatus,
  beslutsfattare: NUXEO_SCHEMA_FIELDS.handling.beslutsfattare,
  avsandare: NUXEO_SCHEMA_FIELDS.handling.avsandare,
  inkommet: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
  riktning: NUXEO_SCHEMA_FIELDS.handling.handlingsriktning,
  sekretess: NUXEO_SCHEMA_FIELDS.handling.sekretess,
  sakerhetsskyddsklassificering: NUXEO_SCHEMA_FIELDS.handling.sakerhetsskyddsklassificering,
  ansvarigHandlaggare: NUXEO_SCHEMA_FIELDS.handling.ansvarigHandlaggare,
  ansvarigEnhet: NUXEO_SCHEMA_FIELDS.handling.ansvarigOrganisatoriskEnhet,
  medhandlaggare: NUXEO_SCHEMA_FIELDS.handling.medhandlaggare,
  granskare: NUXEO_SCHEMA_FIELDS.handling.granskare,
  granskningsdatum: NUXEO_SCHEMA_FIELDS.handling.granskningsdatum,
  granskningskommentar: NUXEO_SCHEMA_FIELDS.handling.granskningskommentar,
  receivedDate: NUXEO_SCHEMA_FIELDS.handling.inkommenDatum,
  upprattadDatum: NUXEO_SCHEMA_FIELDS.handling.upprattadDatum,
  deadline: NUXEO_SCHEMA_FIELDS.handling.utgaendeDatum,
  sender: NUXEO_SCHEMA_FIELDS.handling.avsandare,
  motpart: NUXEO_SCHEMA_FIELDS.handling.mottagare,
  kommentarer: NUXEO_SCHEMA_FIELDS.handling.kommentarer,
  bevarasGallras: NUXEO_SCHEMA_FIELDS.handling.bevarasGallras,
  innehallerPersonuppgifter: NUXEO_SCHEMA_FIELDS.handling.innehallerPersonuppgifterGdpr,
  arkiveradDatum: NUXEO_SCHEMA_FIELDS.handling.arkiveradDatum,
  gallradDatum: NUXEO_SCHEMA_FIELDS.handling.gallradDatum,
  makuleradDatum: NUXEO_SCHEMA_FIELDS.handling.makuleradDatum,
  signerad: NUXEO_SCHEMA_FIELDS.handling.signerad,
  createdBy: NUXEO_SCHEMA_FIELDS.dc.creator,
  modified: NUXEO_SCHEMA_FIELDS.dc.modified,
  counterparty: NUXEO_SCHEMA_FIELDS.handling.motpart,
};
