export interface FormTypes {
  docOptions?: string[];
  skapaOptions?: string[];
  arendeStatus?: string[];
  arendeTyp?: string[];
  handlingsStatus?: string[];
  handlingsTyp?: string[];
  searchLine?: string;
  motpart?: string;
  arende_arendenummer?: string;
  arende_arendemening?: string;
  arende_extern_referens_referens?: string[] | string;
  arende_ansvarig_organisatorisk_enhet?: string[] | string;
  arende_ansvarig_handlaggare?: string[] | string;
  arende_arendet_registrerat_datum_min?: string | Date;
  arende_arendet_registrerat_datum_max?: string | Date;
  arende_beslutat_datum_min?: string | Date;
  arende_beslutat_datum_max?: string | Date;
  arende_arendet_avslutat_datum_min?: string | Date;
  arende_arendet_avslutat_datum_max?: string | Date;
  arende_arendet_arkiverat_datum_min?: string | Date;
  arende_arendet_arkiverat_datum_max?: string | Date;
  arende_arendet_gallrat_datum_min?: string | Date;
  arende_arendet_gallrat_datum_max?: string | Date;
  arende_arendet_makulerat_datum_min?: string | Date;
  arende_arendet_makulerat_datum_max?: string | Date;
  arende_beslutstyp?: string[] | string;
  arende_lagrumsbeskrivning?: string[] | string;
  handling_handlingsnummer?: string;
  handling_handlingsnamn?: string;
  handling_avsandare_namn?: string;
  handling_mottagare_namn?: string;
  handling_extern_referens_referens?: string[] | string;
  handling_inkommen_datum_min?: string | Date;
  handling_inkommen_datum_max?: string | Date;
  handling_upprattad_datum_min?: string | Date;
  handling_upprattad_datum_max?: string | Date;
  handling_beslutat_datum_min?: string | Date;
  handling_beslutat_datum_max?: string | Date;
  handling_expedierad_datum_min?: string | Date;
  handling_expedierad_datum_max?: string | Date;
  handling_forvaringsmedia?: string[];
  handling_fysisk_forvaringsplats?: string;
  handling_lagrumsbeskrivning?: string[] | string;
  arende_handlaggningsstatus?: string[];
  arende_riktning?: string[];
  arende_sakerhetsskyddsklassificering?: string[];
  arende_sekretess?: string[];
  arende_innehaller_personuppgifter_gdpr?: string[];
  handling_handlingsriktning?: string[];
  handling_inkanal_via?: string[];
  handling_signerad?: string[];
  handling_sakerhetsskyddsklassificering?: string[];
  handling_sekretess?: string[];
  handling_bevaras_gallras?: string[];
}
